version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: stackmean-b
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: motoapp
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d